/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package examenlab5progra2_carlosnoé;

/**
 *
 * @author cd507
 */
public class KRUUU extends javax.swing.JPanel {

    /**
     * Creates new form KRUUU
     */
    public KRUUU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        Base = new javax.swing.JPanel();
        MenuLaptop = new javax.swing.JPanel();
        BotonAgregarPc = new java.awt.Button();
        BotonEliminarPc = new java.awt.Button();
        BotonListarPcs = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Menui = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        Base1 = new javax.swing.JPanel();
        MenuLaptop1 = new javax.swing.JPanel();
        BotonAgregarPc1 = new java.awt.Button();
        BotonEliminarPc1 = new java.awt.Button();
        BotonListarPcs1 = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Menui1 = new java.awt.Label();

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("Agregar PC");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLaptop.setBackground(new java.awt.Color(102, 102, 102));

        BotonAgregarPc.setBackground(new java.awt.Color(0, 0, 0));
        BotonAgregarPc.setLabel("button1");
        BotonAgregarPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarPcActionPerformed(evt);
            }
        });

        BotonEliminarPc.setBackground(new java.awt.Color(0, 0, 0));
        BotonEliminarPc.setLabel("button1");

        BotonListarPcs.setBackground(new java.awt.Color(0, 0, 0));
        BotonListarPcs.setLabel("button1");
        BotonListarPcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarPcsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Agregar PC");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setText("Eliminar PC");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setText("Listar PCs");

        Menui.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        Menui.setForeground(new java.awt.Color(0, 0, 0));
        Menui.setText("Menu Laptop");

        javax.swing.GroupLayout MenuLaptopLayout = new javax.swing.GroupLayout(MenuLaptop);
        MenuLaptop.setLayout(MenuLaptopLayout);
        MenuLaptopLayout.setHorizontalGroup(
            MenuLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLaptopLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(MenuLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(BotonAgregarPc, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addGroup(MenuLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListarPcs, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(155, 155, 155)
                .addGroup(MenuLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEliminarPc, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(150, 150, 150))
            .addGroup(MenuLaptopLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(Menui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLaptopLayout.setVerticalGroup(
            MenuLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLaptopLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Menui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(MenuLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(83, 83, 83)
                .addGroup(MenuLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListarPcs, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEliminarPc, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregarPc, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        Menui.getAccessibleContext().setAccessibleName("Menu Laptop");

        Base.add(MenuLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 570));

        Base1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLaptop1.setBackground(new java.awt.Color(102, 102, 102));

        BotonAgregarPc1.setBackground(new java.awt.Color(0, 0, 0));
        BotonAgregarPc1.setLabel("button1");
        BotonAgregarPc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarPc1ActionPerformed(evt);
            }
        });

        BotonEliminarPc1.setBackground(new java.awt.Color(0, 0, 0));
        BotonEliminarPc1.setLabel("button1");

        BotonListarPcs1.setBackground(new java.awt.Color(0, 0, 0));
        BotonListarPcs1.setLabel("button1");
        BotonListarPcs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarPcs1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setText("Agregar PC");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel6.setText("Eliminar PC");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel7.setText("Listar PCs");

        Menui1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        Menui1.setForeground(new java.awt.Color(0, 0, 0));
        Menui1.setText("Menu Laptop");

        javax.swing.GroupLayout MenuLaptop1Layout = new javax.swing.GroupLayout(MenuLaptop1);
        MenuLaptop1.setLayout(MenuLaptop1Layout);
        MenuLaptop1Layout.setHorizontalGroup(
            MenuLaptop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLaptop1Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(MenuLaptop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(BotonAgregarPc1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addGroup(MenuLaptop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListarPcs1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(155, 155, 155)
                .addGroup(MenuLaptop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEliminarPc1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(150, 150, 150))
            .addGroup(MenuLaptop1Layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(Menui1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLaptop1Layout.setVerticalGroup(
            MenuLaptop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLaptop1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Menui1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(MenuLaptop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(83, 83, 83)
                .addGroup(MenuLaptop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListarPcs1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEliminarPc1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregarPc1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        Base1.add(MenuLaptop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 570));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarPcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarPcActionPerformed

    private void BotonListarPcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarPcsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonListarPcsActionPerformed

    private void BotonAgregarPc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarPc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarPc1ActionPerformed

    private void BotonListarPcs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarPcs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonListarPcs1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Base1;
    private java.awt.Button BotonAgregarPc;
    private java.awt.Button BotonAgregarPc1;
    private java.awt.Button BotonEliminarPc;
    private java.awt.Button BotonEliminarPc1;
    private java.awt.Button BotonListarPcs;
    private java.awt.Button BotonListarPcs1;
    private javax.swing.JPanel MenuLaptop;
    private javax.swing.JPanel MenuLaptop1;
    private java.awt.Label Menui;
    private java.awt.Label Menui1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
